### ISSUE TITLE
Images not created by graph.php, et cetera

### ISSUE THREAD

**Issue by jIyajbe** [wjunkin/moodle-mod_ipal#8]
In Moodle 3.2, the ipal module plugin is supposed to generate dynamic histogram graphs by calling graph.php and similar php code. The images fail to appear; they are replaced with the default browser icon for a missing image.

Steps to Reproduce:
1. Using ipal plugin, create a poll.
2. Add at least one question to the poll.
3. Have a user ("student") respond to the poll
(--Note: This step is not necessary, but it affirms that the failure persists after the ipal code receives data to plot)

Expected Results:
A dynamic histogram should

Actual Results:
Broken image, and a live text counter (example: "Total Responses --> 2/10")

Additional information: 
A typical "image address" (obtained from right-clicking on the broken image) is:

http://www.kwheelock.info/moodle/mod/ipal/graph.php?data=0,0&labels=2%20no,1%20yes&total=10

Server Software:
Moodle 3.2
macOS Sierra 10.12.2
PHP Version 5.6.27 (default shipped with OS)

From phpinfo():
GD Support	enabled
GD Version	bundled (2.1.0 compatible)
GIF Read Support	enabled
GIF Create Support	enabled
JPEG Support	enabled
libJPEG Version	9 compatible
PNG Support	enabled
libPNG Version	1.6.20
WBMP Support	enabled
XBM Support	enabled
Directive	Local Value	Master Value
gd.jpeg_ignore_warning	0	0

**Comment by wjunkin** [comment]
Hi, jlyjabe,
Thanks for your interest in IPAL. 
Thanks also for giving such complete information about the problem you are having.
I am running Moodle 3.2. (Moodle 3.2+ (Build: 20161215)) and am not able to duplicate your error. My image is displayed. However, I am viewing the Moodle site using Chrome on a Windows laptop and running the Moodle 3.2 on a Windows server. From the URL of your graph it looks like you may be using a True False questions or. more likely, a multichoice questions with only two options, (with the two options being
2 no
1 yes)
My URL is 
http://localhost/moodle32/mod/ipal/graph.php?data=0,1&labels=True,False&total=10
while yours is 
http://www.kwheelock.info/moodle/mod/ipal/graph.php?data=0,0&labels=2%20no,1%20yes&total=10
I can put your GET information into my URL and get the correct graph for your question to be displayed.
I would like to solve this issue. Evidently this problem is caused the IPAL  program being viewed in the Safari browser, by the IPAL module running on the  macOS Sierra 10.12.2 server, or by something else.
Since I cannot duplicate the problem, I suggest that, if you are willing, you give me two accounts on your Moodle site (one as a teacher and one as a student) and put both into a demo course. I will then see if the problem persists when I use a Chrome browser on a Windows laptop as a teacher to view the graph. If the same problem occurs, we can explore the other two options.
Would you like suggest some other way to investigate how this bug can be solved?
I recommend that we continue this conversation by email and then we can post the final resolution on this github site. My email address is junkinwf@eckerd.edu
There is one other bit of information that may be helpful: In the teacher's screen, where the image is supposed to be displayed, there is a link below it "Open a new window for the graph." When you click on this link a new instance of your browser will open up. I expect that this new window also displays an image indicating that the link to the image is a broken link. However, if it doesn't this will be useful information. 
Again, thanks for your response and for bringing this bug to my attention.
William (Bill) Junkin

**Comment by wjunkin** [comment]
This issue has been resolved. IPAL uses the class graph from the /lib/graphlib.php script in the Moodle core. This class uses the function ImageTTFBBox (and other such functions) that require that the php installation on the server have freetype enabled. An examination of the php info on your server found that freetype was not enabled, thus causing the problem.
